openapi: 3.0.0
info:
  title: Dolzay plugin Api
  description: Documentation for the dolzay plugin Api
  version: 1.0.0
servers:
  - url: http://localhost/prestashop/dz/
paths:
  /micro_process_state/:
    get:
      summary: Micro process state
      description: >-
        It returns the state of the requested micro process which is identified
        by the resource name and the resource id in some cases
      parameters:
        - in: query
          name: resource
          schema:
            type: string
          required: true
        - in: query
          name: resource_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MicroProcessStateResponse'
              examples:
                MicroProcessState:
                  $ref: >-
                    #/components/examples/MicroProcessStateSuccessResponseExample
        '401':
          description: 401 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Unauthenticated:
                  $ref: '#/components/examples/UnauthenticatedResponseExample'
                PluginUnauthorized:
                  $ref: '#/components/examples/PluginUnauthorizedResponseExample'
  /notifications/overview/:
    get:
      summary: Notifications overview
      description: >-
        It returns the the number of all of the notifications and it indicates
        if there is unread notifications
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationsOverviewResponse'
              examples:
                NotificationsOverview:
                  $ref: '#/components/examples/NotificationsOverviewResponseExample'
        '401':
          description: 401 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Unauthenticated:
                  $ref: '#/components/examples/UnauthenticatedResponseExample'
                PluginUnauthorized:
                  $ref: '#/components/examples/PluginUnauthorizedResponseExample'
  /notifications/list/:
    get:
      summary: '[Type] notifications list'
      description: >-
        It returns the notifications list of the type specified in the query
        parameter but if there is a micro process running it returns his state
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum:
              - dormant_orders
              - config_errors
          required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/NotificationsListResponse'
                  - $ref: '#/components/schemas/MicroProcessState'
              examples:
                NotificationsList:
                  $ref: '#/components/examples/NotificationsListResponseExample'
                MicroProcessState:
                  $ref: >-
                    #/components/examples/MicroProcessStateRedirectionResponseExample
        '401':
          description: 401 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Unauthenticated:
                  $ref: '#/components/examples/UnauthenticatedResponseExample'
                PluginUnauthorized:
                  $ref: '#/components/examples/PluginUnauthorizedResponseExample'
  /notifications/mark_all_as_read/:
    put:
      summary: Mark all notifications as read
      description: >-
        It marks all of the unread notifications of the dormant orders and the
        config errors as read
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              enum:
                - dormant_orders
                - config_errors
            example:
              type: dormant_orders
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                MarkAllAsReadResponse:
                  $ref: '#/components/examples/MarkAllAsReadResponseExample'
        '401':
          description: 401 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Unauthenticated:
                  $ref: '#/components/examples/UnauthenticatedResponseExample'
                PluginUnauthorized:
                  $ref: '#/components/examples/PluginUnauthorizedResponseExample'
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - success
            - error
            - redirection
            - unauthorized
            - bad request
        msg:
          type: string
    NotificationsOverviewResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/NotificationsOverview'
    MicroProcessState:
      type: object
      properties:
        finished:
          type: boolean
    MicroProcessStateResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/MicroProcessState'
    NotificationsOverview:
      type: object
      properties:
        notifs_cnt:
          type: integer
        has_unread_notifs:
          type: boolean
    NotificationsList:
      type: object
      properties:
        all_notifs_cnt:
          type: integer
          description: >-
            the number of all of the notifications (dormant orders + config
            errors)
        all_dormant_orders_notifs_cnt:
          type: integer
          description: the number of all of the dormant orders notifications
        all_config_errors_notifs_cnt:
          type: integer
          description: the number of all of the config errors notifications
        read_notifs_cnt:
          type: integer
          description: the number of read dormant orders or config errors notifications
        unread_notifs_cnt:
          type: integer
          description: the number of unread dormant orders or config errors notifications
        notifications:
          type: array
          items:
            type: object
            properties:
              pathname:
                type: string
                description: the link of the dormant order or the config error
              message:
                type: string
              created_at:
                type: string
              viewed:
                type: boolean
    NotificationsListResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/NotificationsList'
  examples:
    SuccessBaseResponseExample:
      value:
        status: success
        msg: ''
    ErrorBaseResponseExample:
      value:
        status: error
        msg: ''
    UnauthenticatedResponseExample:
      value:
        status: unauthorized
        msg: you are not authenticated to do this action
    PluginUnauthorizedResponseExample:
      value:
        status: unauthorized
        msg: you don't have the permission to access the plugin
    LockUnauthorizedResponseExample:
      value:
        status: unauthorized
        msg: you are not the one locking the plugin to perform this action
    NotificationsOverviewResponseExample:
      value:
        status: success
        data:
          notifs_cnt: 50
          has_unread_notifs: true
        msg: ''
    OrderListUnauthorizedResponseExample:
      value:
        status: unauthorized
        msg: you are not authorized to access the order list
    OrderManagementUnauthorizedResponseExample:
      value:
        status: unauthorized
        msg: you are not authorized to access the order management
    CarrierListUnauthorizedResponseExample:
      value:
        status: unauthorized
        msg: you are not authorized to access the carrier list
    CarrierCredentialsUnauthorizedResponseExample:
      value:
        status: unauthorized
        msg: you are not authorized to access the credentials of the carrier
    MicroProcessStateSuccessResponseExample:
      value:
        status: success
        data:
          finished: false
        msg: ''
    MicroProcessStateRedirectionResponseExample:
      value:
        status: redirection
        data:
          finished: false
        msg: ''
    NotificationsListResponseExample:
      value:
        status: success
        data:
          all_notifs_cnt: 50
          all_dormant_orders_notifs_cnt: 25
          all_config_errors_notifs_cnt: 25
          read_notifs_cnt: 5
          unread_notifs_cnt: 20
          notifications:
            - pathname: /orders/10/
              message: ' this order is dormant'
              created_at: 12:35:41 12/01/2024
              viewed: false
            - pathname: /carrier/2/
              message: the carrier _____ must has at least 2 exit states
              created_at: 12:35:41 12/01/2024
              viewed: false
            - pathname: /zone/2/
              message: >-
                the carriers of the zone ____ must collectively cover 100% of
                the volumes coming to this zone
              created_at: 12:35:41 12/01/2024
              viewed: false
            - pathname: /zones/
              message: all the zones must cover collectively all of Tunisia
              created_at: 12:35:41 12/01/2024
              viewed: false
        msg: ''
    MarkAllAsReadResponseExample:
      value:
        status: sucees
        msg: >-
          the process of marking all of the [type] notifications as read has
          just started
